const menuData = [
  // KAFETERIA
  {
    id: "kafe",
    category: "kafeteria",
    category_sq: "Kafeteria",
    category_en: "Coffee Bar",
    category_it: "Caffetteria",
    name: "Kafe",
    name_sq: "Kafe",
    name_en: "Espresso",
    name_it: "Caffè",
    price: 90,
    active: true,
  },
  {
    id: "kafe_fredo",
    category: "kafeteria",
    category_sq: "Kafeteria",
    category_en: "Coffee Bar",
    category_it: "Caffetteria",
    name: "Kafe Fredo",
    name_sq: "Kafe Fredo",
    name_en: "Fredo Coffee",
    name_it: "Caffè Freddo",
    price: 150,
    active: true,
  },
  {
    id: "kakao_ftohte",
    category: "kafeteria",
    category_sq: "Kafeteria",
    category_en: "Coffee Bar",
    category_it: "Caffetteria",
    name: "Kakao e ftohtë",
    name_sq: "Kakao e ftohtë",
    name_en: "Iced Cocoa",
    name_it: "Cacao Freddo",
    price: 200,
    active: true,
  },
  {
    id: "kapucino_ftohte",
    category: "kafeteria",
    category_sq: "Kafeteria",
    category_en: "Coffee Bar",
    category_it: "Caffetteria",
    name: "Kapuçino e Ftohtë",
    name_sq: "Kapuçino e Ftohtë",
    name_en: "Iced Cappuccino",
    name_it: "Cappuccino Freddo",
    price: 220,
    active: true,
  },
  {
    id: "kapucino_kafe",
    category: "kafeteria",
    category_sq: "Kafeteria",
    category_en: "Coffee Bar",
    category_it: "Caffetteria",
    name: "Kapuçino Kafe",
    name_sq: "Kapuçino Kafe",
    name_en: "Cappuccino",
    name_it: "Cappuccino",
    price: 180,
    active: true,
  },
  {
    id: "kapucino_bustine",
    category: "kafeteria",
    category_sq: "Kafeteria",
    category_en: "Coffee Bar",
    category_it: "Caffetteria",
    name: "Kapuçino me Bustinë",
    name_sq: "Kapuçino me Bustinë",
    name_en: "Cappuccino with Sachet",
    name_it: "Cappuccino con Bustina",
    price: 220,
    active: true,
  },
  {
    id: "makiato",
    category: "kafeteria",
    category_sq: "Kafeteria",
    category_en: "Coffee Bar",
    category_it: "Caffetteria",
    name: "Makiato",
    name_sq: "Makiato",
    name_en: "Macchiato",
    name_it: "Macchiato",
    price: 110,
    active: true,
  },
  {
    id: "dekafeinato",
    category: "kafeteria",
    category_sq: "Kafeteria",
    category_en: "Coffee Bar",
    category_it: "Caffetteria",
    name: "Dekafeinato",
    name_sq: "Dekafeinato",
    name_en: "Decaf Coffee",
    name_it: "Decaffeinato",
    price: 120,
    active: true,
  },
  {
    id: "frape",
    category: "kafeteria",
    category_sq: "Kafeteria",
    category_en: "Coffee Bar",
    category_it: "Caffetteria",
    name: "Frape",
    name_sq: "Frape",
    name_en: "Frappe",
    name_it: "Frappè",
    price: 220,
    active: true,
  },
  {
    id: "cokollate_ftohte",
    category: "kafeteria",
    category_sq: "Kafeteria",
    category_en: "Coffee Bar",
    category_it: "Caffetteria",
    name: "Çokollatë e Ftohtë",
    name_sq: "Çokollatë e Ftohtë",
    name_en: "Iced Chocolate",
    name_it: "Cioccolata Fredda",
    price: 220,
    active: true,
  },

  // FRESKUESE
  {
    id: "b52",
    category: "freskuese",
    category_sq: "Freskuese",
    category_en: "Soft Drinks",
    category_it: "Bibite",
    name: "B52",
    name_sq: "B52",
    name_en: "B52 Juice",
    name_it: "Succo B52",
    price: 220,
    active: true,
  },
  {
    id: "ivi",
    category: "freskuese",
    category_sq: "Freskuese",
    category_en: "Soft Drinks",
    category_it: "Bibite",
    name: "IVI",
    name_sq: "IVI",
    name_en: "IVI Juice",
    name_it: "Succo IVI",
    price: 200,
    active: true,
  },
  {
    id: "bravo",
    category: "freskuese",
    category_sq: "Freskuese",
    category_en: "Soft Drinks",
    category_it: "Bibite",
    name: "BRAVO",
    name_sq: "BRAVO",
    name_en: "BRAVO",
    name_it: "BRAVO",
    note_sq: "Pjeshkë / Mollë / Rrushi / Luleshtrydhe",
    note_en: "Peach / Apple / Grape / Strawberry",
    note_it: "Pesca / Mela / Uva / Fragola",
    price: 200,
    active: true,
  },
  {
    id: "amita",
    category: "freskuese",
    category_sq: "Freskuese",
    category_en: "Soft Drinks",
    category_it: "Bibite",
    name: "AMITA",
    name_sq: "AMITA",
    name_en: "AMITA",
    name_it: "AMITA",
    note_sq: "Qershi / Mollë / Banane",
    note_en: "Cherry / Apple / Banana",
    note_it: "Ciliegia / Mela / Banana",
    price: 150,
    active: true,
  },
  {
    id: "coca_cola",
    category: "freskuese",
    category_sq: "Freskuese",
    category_en: "Soft Drinks",
    category_it: "Bibite",
    name: "COCA COLA",
    name_sq: "COCA COLA",
    name_en: "Coca Cola",
    name_it: "Coca Cola",
    price: 200,
    active: true,
  },
  {
    id: "crodino",
    category: "freskuese",
    category_sq: "Freskuese",
    category_en: "Soft Drinks",
    category_it: "Bibite",
    name: "CRODINO",
    name_sq: "CRODINO",
    name_en: "Crodino",
    name_it: "Crodino",
    price: 180,
    active: true,
  },
  {
    id: "fanta",
    category: "freskuese",
    category_sq: "Freskuese",
    category_en: "Soft Drinks",
    category_it: "Bibite",
    name: "Fanta",
    name_sq: "Fanta",
    name_en: "Fanta",
    name_it: "Fanta",
    note_sq: "Portokall / Exo",
    note_en: "Orange / Exotic",
    note_it: "Arancia / Exotic",
    price: 200,
    active: true,
  },
  {
    id: "nescafe_kanace",
    category: "freskuese",
    category_sq: "Freskuese",
    category_en: "Soft Drinks",
    category_it: "Bibite",
    name: "NESCAFE KANACE",
    name_sq: "NESCAFE KANACE",
    name_en: "Nescafe Can",
    name_it: "Nescafe in Lattina",
    price: 200,
    active: true,
  },
  {
    id: "lemon_orange_soda",
    category: "freskuese",
    category_sq: "Freskuese",
    category_en: "Soft Drinks",
    category_it: "Bibite",
    name: "LEMON / ORANGE SODA",
    name_sq: "LEMON / ORANGE SODA",
    name_en: "Lemon / Orange Soda",
    name_it: "Soda Limone / Arancia",
    price: 200,
    active: true,
  },
  {
    id: "ice_tea",
    category: "freskuese",
    category_sq: "Freskuese",
    category_en: "Soft Drinks",
    category_it: "Bibite",
    name: "ICE TEA",
    name_sq: "ICE TEA",
    name_en: "Iced Tea",
    name_it: "Tè Freddo",
    note_sq: "Pjeshkë / Limon",
    note_en: "Peach / Lemon",
    note_it: "Pesca / Limone",
    price: 200,
    active: true,
  },
  {
    id: "pepsi",
    category: "freskuese",
    category_sq: "Freskuese",
    category_en: "Soft Drinks",
    category_it: "Bibite",
    name: "PEPSI",
    name_sq: "PEPSI",
    name_en: "Pepsi",
    name_it: "Pepsi",
    price: 200,
    active: true,
  },
  {
    id: "red_bull",
    category: "freskuese",
    category_sq: "Freskuese",
    category_en: "Soft Drinks",
    category_it: "Bibite",
    name: "RED BULL",
    name_sq: "RED BULL",
    name_en: "Red Bull",
    name_it: "Red Bull",
    price: 350,
    active: true,
  },
  {
    id: "sprite",
    category: "freskuese",
    category_sq: "Freskuese",
    category_en: "Soft Drinks",
    category_it: "Bibite",
    name: "SPRITE",
    name_sq: "SPRITE",
    name_en: "Sprite",
    name_it: "Sprite",
    price: 200,
    active: true,
  },
  {
    id: "schweppes",
    category: "freskuese",
    category_sq: "Freskuese",
    category_en: "Soft Drinks",
    category_it: "Bibite",
    name: "SCHWEPPES",
    name_sq: "SCHWEPPES",
    name_en: "Schweppes",
    name_it: "Schweppes",
    price: 180,
    active: true,
  },
  {
    id: "uje_gazuar",
    category: "freskuese",
    category_sq: "Freskuese",
    category_en: "Soft Drinks",
    category_it: "Bibite",
    name: "Ujë / ujë i gazuar",
    name_sq: "Ujë / ujë i gazuar",
    name_en: "Water / Sparkling Water",
    name_it: "Acqua / Acqua Frizzante",
    price: 90,
    active: true,
  },
  {
    id: "uje_vitamin_tepelena",
    category: "freskuese",
    category_sq: "Freskuese",
    category_en: "Soft Drinks",
    category_it: "Bibite",
    name: "Ujë Vitamin Tepelena",
    name_sq: "Ujë Vitamin Tepelena",
    name_en: "Vitamin Water Tepelena",
    name_it: "Acqua Vitaminica Tepelena",
    price: 170,
    active: true,
  },

  // BIRRA
  {
    id: "corona",
    category: "birra",
    category_sq: "Birra",
    category_en: "Beer",
    category_it: "Birra",
    name: "CORONA",
    name_sq: "CORONA",
    name_en: "Corona",
    name_it: "Corona",
    price: 450,
    active: true,
  },
  {
    id: "peroni",
    category: "birra",
    category_sq: "Birra",
    category_en: "Beer",
    category_it: "Birra",
    name: "PERONI",
    name_sq: "PERONI",
    name_en: "Peroni",
    name_it: "Peroni",
    price: 250,
    active: true,
  },
  {
    id: "heineken",
    category: "birra",
    category_sq: "Birra",
    category_en: "Beer",
    category_it: "Birra",
    name: "HEINEKEN",
    name_sq: "HEINEKEN",
    name_en: "Heineken",
    name_it: "Heineken",
    price: 350,
    active: true,
  },
  {
    id: "paulaner",
    category: "birra",
    category_sq: "Birra",
    category_en: "Beer",
    category_it: "Birra",
    name: "PAULANER",
    name_sq: "PAULANER",
    name_en: "Paulaner",
    name_it: "Paulaner",
    price: 450,
    active: true,
  },
  {
    id: "korca",
    category: "birra",
    category_sq: "Birra",
    category_en: "Beer",
    category_it: "Birra",
    name: "Korça",
    name_sq: "Korça",
    name_en: "Korça Beer",
    name_it: "Birra Korça",
    price: 220,
    active: true,
  },

  // COCKTAILS
  {
    id: "gin_lemon_tonic",
    category: "cocktails",
    category_sq: "Cocktails",
    category_en: "Cocktails",
    category_it: "Cocktail",
    name: "Gin lemon / tonic",
    name_sq: "Gin lemon / tonic",
    name_en: "Gin Lemon / Tonic",
    name_it: "Gin Lemon / Tonic",
    price: 650,
    active: true,
  },
  {
    id: "jager_redbull",
    category: "cocktails",
    category_sq: "Cocktails",
    category_en: "Cocktails",
    category_it: "Cocktail",
    name: "Jager redbull",
    name_sq: "Jager redbull",
    name_en: "Jager Red Bull",
    name_it: "Jager Red Bull",
    price: 600,
    active: true,
  },
  {
    id: "negroni",
    category: "cocktails",
    category_sq: "Cocktails",
    category_en: "Cocktails",
    category_it: "Cocktail",
    name: "NEGRONI",
    name_sq: "NEGRONI",
    name_en: "Negroni",
    name_it: "Negroni",
    price: 700,
    active: true,
  },
  {
    id: "koktej_pa_alkool",
    category: "cocktails",
    category_sq: "Cocktails",
    category_en: "Cocktails",
    category_it: "Cocktail",
    name: "Koktej pa Alkool",
    name_sq: "Koktej pa Alkool",
    name_en: "Non-Alcoholic Cocktail",
    name_it: "Cocktail Analcolico",
    price: 550,
    active: true,
  },
  {
    id: "vodka_lemon",
    category: "cocktails",
    category_sq: "Cocktails",
    category_en: "Cocktails",
    category_it: "Cocktail",
    name: "Vodka lemon",
    name_sq: "Vodka lemon",
    name_en: "Vodka Lemon",
    name_it: "Vodka Lemon",
    price: 600,
    active: true,
  },
  {
    id: "vodka_redbull",
    category: "cocktails",
    category_sq: "Cocktails",
    category_en: "Cocktails",
    category_it: "Cocktail",
    name: "Vodka redbull",
    name_sq: "Vodka redbull",
    name_en: "Vodka Red Bull",
    name_it: "Vodka Red Bull",
    price: 650,
    active: true,
  },
  {
    id: "vodka_sour",
    category: "cocktails",
    category_sq: "Cocktails",
    category_en: "Cocktails",
    category_it: "Cocktail",
    name: "Vodka sour",
    name_sq: "Vodka sour",
    name_en: "Vodka Sour",
    name_it: "Vodka Sour",
    price: 650,
    active: true,
  },
  {
    id: "whiskey_sour",
    category: "cocktails",
    category_sq: "Cocktails",
    category_en: "Cocktails",
    category_it: "Cocktail",
    name: "Whiskey sour",
    name_sq: "Whiskey sour",
    name_en: "Whiskey Sour",
    name_it: "Whiskey Sour",
    price: 650,
    active: true,
  },
  {
    id: "gin_sour",
    category: "cocktails",
    category_sq: "Cocktails",
    category_en: "Cocktails",
    category_it: "Cocktail",
    name: "Gin sour",
    name_sq: "Gin sour",
    name_en: "Gin Sour",
    name_it: "Gin Sour",
    price: 650,
    active: true,
  },
  {
    id: "mojito",
    category: "cocktails",
    category_sq: "Cocktails",
    category_en: "Cocktails",
    category_it: "Cocktail",
    name: "MOJITO",
    name_sq: "MOJITO",
    name_en: "Mojito",
    name_it: "Mojito",
    price: 600,
    active: true,
  },
  {
    id: "espresso_martini",
    category: "cocktails",
    category_sq: "Cocktails",
    category_en: "Cocktails",
    category_it: "Cocktail",
    name: "ESPRESSO MARTINI",
    name_sq: "ESPRESSO MARTINI",
    name_en: "Espresso Martini",
    name_it: "Espresso Martini",
    price: 650,
    active: true,
  },
  {
    id: "aperol_spritz",
    category: "cocktails",
    category_sq: "Cocktails",
    category_en: "Cocktails",
    category_it: "Cocktail",
    name: "APEROL SPRITZ",
    name_sq: "APEROL SPRITZ",
    name_en: "Aperol Spritz",
    name_it: "Aperol Spritz",
    price: 500,
    active: true,
  },
  {
    id: "margarita",
    category: "cocktails",
    category_sq: "Cocktails",
    category_en: "Cocktails",
    category_it: "Cocktail",
    name: "MARGARITA",
    name_sq: "MARGARITA",
    name_en: "Margarita",
    name_it: "Margarita",
    price: 650,
    active: true,
  },
  {
    id: "pina_colada",
    category: "cocktails",
    category_sq: "Cocktails",
    category_en: "Cocktails",
    category_it: "Cocktail",
    name: "PINA COLADA",
    name_sq: "PINA COLADA",
    name_en: "Piña Colada",
    name_it: "Piña Colada",
    price: 700,
    active: true,
  },
  {
    id: "cuba_libre",
    category: "cocktails",
    category_sq: "Cocktails",
    category_en: "Cocktails",
    category_it: "Cocktail",
    name: "CUBA LIBRE",
    name_sq: "CUBA LIBRE",
    name_en: "Cuba Libre",
    name_it: "Cuba Libre",
    price: 650,
    active: true,
  },
  {
    id: "passion_strawberry_mojito",
    category: "cocktails",
    category_sq: "Cocktails",
    category_en: "Cocktails",
    category_it: "Cocktail",
    name: "Passion Fruit / Strawberry Mojito",
    name_sq: "Passion Fruit / Strawberry Mojito",
    name_en: "Passion Fruit / Strawberry Mojito",
    name_it: "Mojito Passion Fruit / Fragola",
    price: 650,
    active: true,
  },
  {
    id: "sunset_at_vale",
    category: "cocktails",
    category_sq: "Cocktails",
    category_en: "Cocktails",
    category_it: "Cocktail",
    name: "Sunset at Vale",
    name_sq: "Sunset at Vale",
    name_en: "Sunset at Vale",
    name_it: "Sunset at Vale",
    price: 500,
    active: true,
  },
  {
    id: "summer_echo",
    category: "cocktails",
    category_sq: "Cocktails",
    category_en: "Cocktails",
    category_it: "Cocktail",
    name: "SUMMER ECHO",
    name_sq: "SUMMER ECHO",
    name_en: "Summer Echo",
    name_it: "Summer Echo",
    price: 600,
    active: true,
  },
  {
    id: "black_white_russian",
    category: "cocktails",
    category_sq: "Cocktails",
    category_en: "Cocktails",
    category_it: "Cocktail",
    name: "Black / white russian",
    name_sq: "Black / white russian",
    name_en: "Black / White Russian",
    name_it: "Black / White Russian",
    price: 500,
    active: true,
  },

  // PIJE ALKOOLIKE
  {
    id: "dictador_12",
    category: "pije-alkoolike",
    category_sq: "Pije Alkoolike",
    category_en: "Spirits",
    category_it: "Alcolici",
    name: "DICTADOR 12",
    name_sq: "DICTADOR 12",
    name_en: "Dictador 12",
    name_it: "Dictador 12",
    price: 600,
    active: true,
  },
  {
    id: "diplomatico",
    category: "pije-alkoolike",
    category_sq: "Pije Alkoolike",
    category_en: "Spirits",
    category_it: "Alcolici",
    name: "DIPLOMATICO",
    name_sq: "DIPLOMATICO",
    name_en: "Diplomatico",
    name_it: "Diplomatico",
    price: 700,
    active: true,
  },
  {
    id: "disarono",
    category: "pije-alkoolike",
    category_sq: "Pije Alkoolike",
    category_en: "Spirits",
    category_it: "Alcolici",
    name: "DISARONO",
    name_sq: "DISARONO",
    name_en: "Disaronno",
    name_it: "Disaronno",
    price: 300,
    active: true,
  },
  {
    id: "gin_mare",
    category: "pije-alkoolike",
    category_sq: "Pije Alkoolike",
    category_en: "Spirits",
    category_it: "Alcolici",
    name: "GIN MARE",
    name_sq: "GIN MARE",
    name_en: "Gin Mare",
    name_it: "Gin Mare",
    price: 600,
    active: true,
  },
  {
    id: "jack_gentleman",
    category: "pije-alkoolike",
    category_sq: "Pije Alkoolike",
    category_en: "Spirits",
    category_it: "Alcolici",
    name: "JACK GENTLEMAN",
    name_sq: "JACK GENTLEMAN",
    name_en: "Jack Gentleman",
    name_it: "Jack Gentleman",
    price: 500,
    active: true,
  },
  {
    id: "jagermeister",
    category: "pije-alkoolike",
    category_sq: "Pije Alkoolike",
    category_en: "Spirits",
    category_it: "Alcolici",
    name: "JAGERMEISTER",
    name_sq: "JAGERMEISTER",
    name_en: "Jägermeister",
    name_it: "Jägermeister",
    price: 400,
    active: true,
  },
  {
    id: "molinari_sambuca",
    category: "pije-alkoolike",
    category_sq: "Pije Alkoolike",
    category_en: "Spirits",
    category_it: "Alcolici",
    name: "MOLINARI SAMBUCA",
    name_sq: "MOLINARI SAMBUCA",
    name_en: "Molinari Sambuca",
    name_it: "Molinari Sambuca",
    price: 300,
    active: true,
  },
  {
    id: "uzo",
    category: "pije-alkoolike",
    category_sq: "Pije Alkoolike",
    category_en: "Spirits",
    category_it: "Alcolici",
    name: "UZO",
    name_sq: "UZO",
    name_en: "Ouzo",
    name_it: "Ouzo",
    price: 300,
    active: true,
  },
  {
    id: "vodka_belvedere",
    category: "pije-alkoolike",
    category_sq: "Pije Alkoolike",
    category_en: "Spirits",
    category_it: "Alcolici",
    name: "VODKA BELVEDERE",
    name_sq: "VODKA BELVEDERE",
    name_en: "Belvedere Vodka",
    name_it: "Vodka Belvedere",
    price: 600,
    active: true,
  },
  {
    id: "chivas_regal",
    category: "pije-alkoolike",
    category_sq: "Pije Alkoolike",
    category_en: "Spirits",
    category_it: "Alcolici",
    name: "CHIVAS REGAL",
    name_sq: "CHIVAS REGAL",
    name_en: "Chivas Regal",
    name_it: "Chivas Regal",
    price: 500,
    active: true,
  },
  {
    id: "courvoisier",
    category: "pije-alkoolike",
    category_sq: "Pije Alkoolike",
    category_en: "Spirits",
    category_it: "Alcolici",
    name: "Courvoisier",
    name_sq: "Courvoisier",
    name_en: "Courvoisier",
    name_it: "Courvoisier",
    price: 500,
    active: true,
  },
  {
    id: "fernet_branca",
    category: "pije-alkoolike",
    category_sq: "Pije Alkoolike",
    category_en: "Spirits",
    category_it: "Alcolici",
    name: "FERNET BRANCA",
    name_sq: "FERNET BRANCA",
    name_en: "Fernet Branca",
    name_it: "Fernet Branca",
    price: 300,
    active: true,
  },
  {
    id: "jack_daniels",
    category: "pije-alkoolike",
    category_sq: "Pije Alkoolike",
    category_en: "Spirits",
    category_it: "Alcolici",
    name: "JACK DANIELS",
    name_sq: "JACK DANIELS",
    name_en: "Jack Daniel's",
    name_it: "Jack Daniel's",
    price: 350,
    active: true,
  },
  {
    id: "gin_hendricks",
    category: "pije-alkoolike",
    category_sq: "Pije Alkoolike",
    category_en: "Spirits",
    category_it: "Alcolici",
    name: "GIN HENDRICKS",
    name_sq: "GIN HENDRICKS",
    name_en: "Hendrick's Gin",
    name_it: "Gin Hendrick's",
    price: 500,
    active: true,
  },

  // VERE
  {
    id: "gote_vere",
    category: "vere",
    category_sq: "Verë",
    category_en: "Wine",
    category_it: "Vino",
    name: "Gotë verë",
    name_sq: "Gotë verë",
    name_en: "Glass of Wine",
    name_it: "Calice di Vino",
    price: 450,
    active: true,
  },
  {
    id: "prosecco_gote_shishe",
    category: "vere",
    category_sq: "Verë",
    category_en: "Wine",
    category_it: "Vino",
    name: "Gotë / Shishe Prosecco",
    name_sq: "Gotë / Shishe Prosecco",
    name_en: "Prosecco Glass / Bottle",
    name_it: "Prosecco Calice / Bottiglia",
    price: 500,
    price_label_sq: "500 / 2000 LEK",
    price_label_en: "500 / 2000 LEK",
    price_label_it: "500 / 2000 LEK",
    bottle_price: 2000,
    active: true,
  },
  {
    id: "chardonnay",
    category: "vere",
    category_sq: "Verë",
    category_en: "Wine",
    category_it: "Vino",
    name: "CHARDONNAY",
    name_sq: "CHARDONNAY",
    name_en: "Chardonnay",
    name_it: "Chardonnay",
    price: 2000,
    active: true,
  },
  {
    id: "pinot_grigio",
    category: "vere",
    category_sq: "Verë",
    category_en: "Wine",
    category_it: "Vino",
    name: "PINOT GRIGIO",
    name_sq: "PINOT GRIGIO",
    name_en: "Pinot Grigio",
    name_it: "Pinot Grigio",
    price: 2500,
    active: true,
  },
  {
    id: "greco_di_tufo",
    category: "vere",
    category_sq: "Verë",
    category_en: "Wine",
    category_it: "Vino",
    name: "GRECO DI TUFO",
    name_sq: "GRECO DI TUFO",
    name_en: "Greco di Tufo",
    name_it: "Greco di Tufo",
    price: 3000,
    active: true,
  },
  {
    id: "gewurztraminer",
    category: "vere",
    category_sq: "Verë",
    category_en: "Wine",
    category_it: "Vino",
    name: "GEWÜRZTRAMINER",
    name_sq: "GEWÜRZTRAMINER",
    name_en: "Gewürztraminer",
    name_it: "Gewürztraminer",
    price: 4000,
    active: true,
  },

  // SALLATE & SHOQERUESE
  {
    id: "sallate_greke",
    category: "sallate-shoqeruese",
    category_sq: "Sallatë & Shoqëruese",
    category_en: "Salads & Sides",
    category_it: "Insalate & Contorni",
    name: "Sallatë greke",
    name_sq: "Sallatë greke",
    name_en: "Greek Salad",
    name_it: "Insalata Greca",
    price: 500,
    active: true,
  },
  {
    id: "sallate_jeshile",
    category: "sallate-shoqeruese",
    category_sq: "Sallatë & Shoqëruese",
    category_en: "Salads & Sides",
    category_it: "Insalate & Contorni",
    name: "Sallatë jeshile",
    name_sq: "Sallatë jeshile",
    name_en: "Green Salad",
    name_it: "Insalata Verde",
    price: 420,
    active: true,
  },
  {
    id: "shalqi_djathe_mente",
    category: "sallate-shoqeruese",
    category_sq: "Sallatë & Shoqëruese",
    category_en: "Salads & Sides",
    category_it: "Insalate & Contorni",
    name: "Shalqi dhe djathë dhe mente",
    name_sq: "Shalqi dhe djathë dhe mente",
    name_en: "Watermelon with Cheese and Mint",
    name_it: "Anguria con Formaggio e Menta",
    price: 400,
    active: true,
  },
  {
    id: "djathe_bardhe",
    category: "sallate-shoqeruese",
    category_sq: "Sallatë & Shoqëruese",
    category_en: "Salads & Sides",
    category_it: "Insalate & Contorni",
    name: "Djathë i bardhë",
    name_sq: "Djathë i bardhë",
    name_en: "White Cheese",
    name_it: "Formaggio Bianco",
    price: 300,
    active: true,
  },
  {
    id: "perime_zgare",
    category: "sallate-shoqeruese",
    category_sq: "Sallatë & Shoqëruese",
    category_en: "Salads & Sides",
    category_it: "Insalate & Contorni",
    name: "Perime Zgare",
    name_sq: "Perime Zgare",
    name_en: "Grilled Vegetables",
    name_it: "Verdure alla Griglia",
    price: 400,
    active: true,
  },
  {
    id: "french_fries",
    category: "sallate-shoqeruese",
    category_sq: "Sallatë & Shoqëruese",
    category_en: "Salads & Sides",
    category_it: "Insalate & Contorni",
    name: "French fries",
    name_sq: "French fries",
    name_en: "French Fries",
    name_it: "Patatine Fritte",
    price: 300,
    active: true,
  },
  {
    id: "salce_kosi",
    category: "sallate-shoqeruese",
    category_sq: "Sallatë & Shoqëruese",
    category_en: "Salads & Sides",
    category_it: "Insalate & Contorni",
    name: "Salcë Kosi",
    name_sq: "Salcë Kosi",
    name_en: "Yogurt Sauce",
    name_it: "Salsa allo Yogurt",
    price: 200,
    active: true,
  },

  // SPECIALITETE DETI
  {
    id: "koce_zgare",
    category: "specialitete-deti",
    category_sq: "Specialitete Deti",
    category_en: "Seafood Specials",
    category_it: "Specialità di Mare",
    name: "Koce Zgare",
    name_sq: "Koce Zgare",
    name_en: "Grilled Gilthead Bream",
    name_it: "Orata alla Griglia",
    price: 1100,
    active: true,
  },
  {
    id: "levrek_zgare",
    category: "specialitete-deti",
    category_sq: "Specialitete Deti",
    category_en: "Seafood Specials",
    category_it: "Specialità di Mare",
    name: "Levrek zgare",
    name_sq: "Levrek zgare",
    name_en: "Grilled Sea Bass",
    name_it: "Branzino alla Griglia",
    price: 1200,
    active: true,
  },
  {
    id: "mix_deti_zgare",
    category: "specialitete-deti",
    category_sq: "Specialitete Deti",
    category_en: "Seafood Specials",
    category_it: "Specialità di Mare",
    name: "Mix deti zgare",
    name_sq: "Mix deti zgare",
    name_en: "Mixed Grilled Seafood",
    name_it: "Mix di Mare alla Griglia",
    price: 1500,
    active: true,
  },
  {
    id: "karkalec_zgare",
    category: "specialitete-deti",
    category_sq: "Specialitete Deti",
    category_en: "Seafood Specials",
    category_it: "Specialità di Mare",
    name: "Karkalec zgare",
    name_sq: "Karkalec zgare",
    name_en: "Grilled Shrimp",
    name_it: "Gamberi alla Griglia",
    price: 1100,
    active: true,
  },
  {
    id: "kallamar_zgare",
    category: "specialitete-deti",
    category_sq: "Specialitete Deti",
    category_en: "Seafood Specials",
    category_it: "Specialità di Mare",
    name: "Kallamar zgare",
    name_sq: "Kallamar zgare",
    name_en: "Grilled Squid",
    name_it: "Calamari alla Griglia",
    price: 1000,
    active: true,
  },
  {
    id: "qofte_gaforre",
    category: "specialitete-deti",
    category_sq: "Specialitete Deti",
    category_en: "Seafood Specials",
    category_it: "Specialità di Mare",
    name: "Qofte gaforre",
    name_sq: "Qofte gaforre",
    name_en: "Crab Cakes",
    name_it: "Polpette di Granchio",
    price: 500,
    active: true,
  },
  {
    id: "acuge_marinuara",
    category: "specialitete-deti",
    category_sq: "Specialitete Deti",
    category_en: "Seafood Specials",
    category_it: "Specialità di Mare",
    name: "Acuge të marinuara",
    name_sq: "Acuge të marinuara",
    name_en: "Marinated Anchovies",
    name_it: "Acciughe Marinate",
    price: 550,
    active: true,
  },

  // PULE & GRILL
  {
    id: "chicken_wings",
    category: "pule-grill",
    category_sq: "Pulë & Grill",
    category_en: "Chicken & Grill",
    category_it: "Pollo & Grill",
    name: "Chicken wings",
    name_sq: "Chicken wings",
    name_en: "Chicken Wings",
    name_it: "Alette di Pollo",
    price: 480,
    active: true,
  },
  {
    id: "shishqebap_pule",
    category: "pule-grill",
    category_sq: "Pulë & Grill",
    category_en: "Chicken & Grill",
    category_it: "Pollo & Grill",
    name: "Shishqebap pule",
    name_sq: "Shishqebap pule",
    name_en: "Chicken Skewer",
    name_it: "Spiedino di Pollo",
    price: 120,
    active: true,
  },
  {
    id: "fileto_pule_zgare",
    category: "pule-grill",
    category_sq: "Pulë & Grill",
    category_en: "Chicken & Grill",
    category_it: "Pollo & Grill",
    name: "Fileto pule zgare",
    name_sq: "Fileto pule zgare",
    name_en: "Grilled Chicken Fillet",
    name_it: "Filetto di Pollo alla Griglia",
    price: 700,
    active: true,
  },

  // PIZZA
  {
    id: "pizza_margherita",
    category: "pizza",
    category_sq: "Pizza",
    category_en: "Pizza",
    category_it: "Pizza",
    name: "Pizza margherita",
    name_sq: "Pizza margherita",
    name_en: "Pizza Margherita",
    name_it: "Pizza Margherita",
    price: 600,
    active: true,
  },
  {
    id: "pizza_proshute",
    category: "pizza",
    category_sq: "Pizza",
    category_en: "Pizza",
    category_it: "Pizza",
    name: "Pizza proshutë",
    name_sq: "Pizza proshutë",
    name_en: "Ham Pizza",
    name_it: "Pizza Prosciutto",
    price: 700,
    active: true,
  },
  {
    id: "pizza_pikante",
    category: "pizza",
    category_sq: "Pizza",
    category_en: "Pizza",
    category_it: "Pizza",
    name: "Pizza pikante",
    name_sq: "Pizza pikante",
    name_en: "Spicy Pizza",
    name_it: "Pizza Piccante",
    price: 750,
    active: true,
  },
  {
    id: "pizza_tono",
    category: "pizza",
    category_sq: "Pizza",
    category_en: "Pizza",
    category_it: "Pizza",
    name: "Pizza tono",
    name_sq: "Pizza tono",
    name_en: "Tuna Pizza",
    name_it: "Pizza Tonno",
    price: 800,
    active: true,
  },
  {
    id: "pizza_kapricoza",
    category: "pizza",
    category_sq: "Pizza",
    category_en: "Pizza",
    category_it: "Pizza",
    name: "Pizza kapricoza",
    name_sq: "Pizza kapricoza",
    name_en: "Capricciosa Pizza",
    name_it: "Pizza Capricciosa",
    price: 850,
    active: true,
  },

  // STREET FOOD
  {
    id: "sanduic_proshute",
    category: "street-food",
    category_sq: "Street Food & Quick Bites",
    category_en: "Street Food & Quick Bites",
    category_it: "Street Food & Quick Bites",
    name: "Sanduiç Proshutë",
    name_sq: "Sanduiç Proshutë",
    name_en: "Ham Sandwich",
    name_it: "Panino al Prosciutto",
    price: 300,
    active: true,
  },
  {
    id: "sanduic_pikant",
    category: "street-food",
    category_sq: "Street Food & Quick Bites",
    category_en: "Street Food & Quick Bites",
    category_it: "Street Food & Quick Bites",
    name: "Sanduiç Pikant",
    name_sq: "Sanduiç Pikant",
    name_en: "Spicy Sandwich",
    name_it: "Panino Piccante",
    price: 320,
    active: true,
  },
  {
    id: "club_sandwich",
    category: "street-food",
    category_sq: "Street Food & Quick Bites",
    category_en: "Street Food & Quick Bites",
    category_it: "Street Food & Quick Bites",
    name: "CLUB SANDWICH",
    name_sq: "CLUB SANDWICH",
    name_en: "Club Sandwich",
    name_it: "Club Sandwich",
    price: 480,
    active: true,
  },
  {
    id: "greek_chicken_pita",
    category: "street-food",
    category_sq: "Street Food & Quick Bites",
    category_en: "Street Food & Quick Bites",
    category_it: "Street Food & Quick Bites",
    name: "GREEK CHICKEN PITA",
    name_sq: "GREEK CHICKEN PITA",
    name_en: "Greek Chicken Pita",
    name_it: "Pita Greca con Pollo",
    price: 650,
    active: true,
  },

  // MENGJESI
  {
    id: "tost",
    category: "mengjesi",
    category_sq: "Mëngjesi",
    category_en: "Breakfast",
    category_it: "Colazione",
    name: "Tost",
    name_sq: "Tost",
    name_en: "Toast",
    name_it: "Toast",
    price: 180,
    active: true,
  },
  {
    id: "byrek_sfogliata",
    category: "mengjesi",
    category_sq: "Mëngjesi",
    category_en: "Breakfast",
    category_it: "Colazione",
    name: "Byrek sfogliata",
    name_sq: "Byrek sfogliata",
    name_en: "Puff Pastry Byrek",
    name_it: "Byrek di Sfoglia",
    price: 90,
    active: true,
  },
  {
    id: "croissant",
    category: "mengjesi",
    category_sq: "Mëngjesi",
    category_en: "Breakfast",
    category_it: "Colazione",
    name: "CROISSANT",
    name_sq: "CROISSANT",
    name_en: "Croissant",
    name_it: "Croissant",
    price: 130,
    active: true,
  },
  {
    id: "gote_qumesht",
    category: "mengjesi",
    category_sq: "Mëngjesi",
    category_en: "Breakfast",
    category_it: "Colazione",
    name: "Gotë qumësht",
    name_sq: "Gotë qumësht",
    name_en: "Glass of Milk",
    name_it: "Bicchiere di Latte",
    price: 150,
    active: true,
  },

  // WAFFLE
  {
    id: "waffle_recel_djathe",
    category: "waffle",
    category_sq: "Waffle",
    category_en: "Waffle",
    category_it: "Waffle",
    name: "Waffle Reçel Shtëpie + Djathë",
    name_sq: "Waffle Reçel Shtëpie + Djathë",
    name_en: "Waffle with Homemade Jam + Cheese",
    name_it: "Waffle con Marmellata Artigianale + Formaggio",
    note_sq: "08:00 - 11:00 dhe 17:00 - 20:00",
    note_en: "08:00 - 11:00 and 17:00 - 20:00",
    note_it: "08:00 - 11:00 e 17:00 - 20:00",
    price: 500,
    active: true,
  },
  {
    id: "waffle_coko_banane",
    category: "waffle",
    category_sq: "Waffle",
    category_en: "Waffle",
    category_it: "Waffle",
    name: "Waffle Coko - Banane",
    name_sq: "Waffle Coko - Banane",
    name_en: "Chocolate Banana Waffle",
    name_it: "Waffle Cioccolato e Banana",
    price: 450,
    active: true,
  },
  {
    id: "waffle_coko",
    category: "waffle",
    category_sq: "Waffle",
    category_en: "Waffle",
    category_it: "Waffle",
    name: "Waffle Coko",
    name_sq: "Waffle Coko",
    name_en: "Chocolate Waffle",
    name_it: "Waffle al Cioccolato",
    price: 400,
    active: true,
  },
  {
    id: "waffle_pistachio",
    category: "waffle",
    category_sq: "Waffle",
    category_en: "Waffle",
    category_it: "Waffle",
    name: "Waffle Pistachio",
    name_sq: "Waffle Pistachio",
    name_en: "Pistachio Waffle",
    name_it: "Waffle al Pistacchio",
    price: 500,
    active: true,
  },

  // BURGER
  {
    id: "burger_vici_fries",
    category: "burger",
    category_sq: "Burger",
    category_en: "Burger",
    category_it: "Burger",
    name: "Burger vici + fries",
    name_sq: "Burger vici + fries",
    name_en: "Beef Burger + Fries",
    name_it: "Burger di Manzo + Patatine",
    price: 700,
    active: true,
  },
  {
    id: "burger_pule_fries",
    category: "burger",
    category_sq: "Burger",
    category_en: "Burger",
    category_it: "Burger",
    name: "Burger pule + fries",
    name_sq: "Burger pule + fries",
    name_en: "Chicken Burger + Fries",
    name_it: "Burger di Pollo + Patatine",
    price: 650,
    active: true,
  },
  {
    id: "double_burger_max_fries",
    category: "burger",
    category_sq: "Burger",
    category_en: "Burger",
    category_it: "Burger",
    name: "DOUBLE BURGER MAX + FRIES",
    name_sq: "DOUBLE BURGER MAX + FRIES",
    name_en: "Double Burger Max + Fries",
    name_it: "Double Burger Max + Patatine",
    price: 850,
    active: true,
  },

  // PER TE GJITHE NE
  {
    id: "tave_zog_oriz_jufka_4",
    category: "per-te-gjithe-ne",
    category_sq: "Për të Gjithë Ne",
    category_en: "For Sharing",
    category_it: "Per Tutti",
    name: "TAVE ZOG FSHATI ME ORIZ / JUFKA 4 persona",
    name_sq: "TAVE ZOG FSHATI ME ORIZ / JUFKA 4 persona",
    name_en: "Country Chicken Tray with Rice / Jufka for 4 people",
    name_it: "Teglia di Pollo Ruspante con Riso / Jufka per 4 persone",
    note_sq: "Vonon 1 orë (na mirëkuptoni ;))",
    note_en: "Takes 1 hour (thank you for understanding ;))",
    note_it: "Richiede 1 ora (grazie per la comprensione ;))",
    price: 2200,
    active: true,
  },
  {
    id: "tave_zog_jufka_6",
    category: "per-te-gjithe-ne",
    category_sq: "Për të Gjithë Ne",
    category_en: "For Sharing",
    category_it: "Per Tutti",
    name: "TAVE ZOG FSHATI ME JUFKA 6 persona",
    name_sq: "TAVE ZOG FSHATI ME JUFKA 6 persona",
    name_en: "Country Chicken Tray with Jufka for 6 people",
    name_it: "Teglia di Pollo Ruspante con Jufka per 6 persone",
    note_sq: "Vonon 1 orë (na mirëkuptoni ;))",
    note_en: "Takes 1 hour (thank you for understanding ;))",
    note_it: "Richiede 1 ora (grazie per la comprensione ;))",
    price: 3300,
    active: true,
  },
];

window.menuData = menuData;